### PR TITLE
Move blog post form fields to primary tabs

### PR DESCRIPTION
**Pull request by bennothommo**
For whatever reason, the Blog plugin has traditionally had its fields in the secondary tabs whilst still using the "fancy layout" look that a lot of plugins use. I've always thought it looked a bit odd and inconsistent. This PR moves them back to the primary tabs, which makes it look more inline with how the other "fancy layout" screens look.

I've attached screenshots of how it looks below - note that this is a site that has custom colouring and has replaced the Markdown editor with a rich editor.

Screen Shot 2022-10-24 at 3 44 10 pm

Screen Shot 2022-10-24 at 3 43 59 pm

This might be a BC break, however, for plugins that try and extend the fields of the Blog plugin (for example, those plugins or code snippets that switch the editor to a rich editor), so it might need to be released as a major version.

### CODE REVIEW

**Review by LukeTowers — APPROVED** [review]
I'm fine with this, although technically it should be a version bump yes. Not sure if I would call it a major version bump though, any thoughts?

**Comment by bennothommo** [comment]
@LukeTowers I mentioned the major bump because of the BC break. There's people probably using @mjauvin's [Winter trick](https://wintertricks.com/tricks/use-a-rich-editor-form-widget-as-the-winterblog-post-editor) that won't work with this change.

**Comment by LukeTowers** [comment]
@bennothommo could we avoid the BC break by making the change in that event listener but with the lowest priority set so it runs after everything else?

**Comment by bennothommo** [comment]
Do you mean switching the fields to the primary tabs as part of an event listener? Seems kinda dirty :P

**Comment by LukeTowers** [comment]
It is, but also BC friendly :)

**Comment by LukeTowers** [comment]
Could even just do it in the Tailwind UI plugin since the issue with consistency is mostly with that I'd imagine.

**Pull request merged**
