### PR TITLE
Add missing translations, remove duplicate ones

### PR DESCRIPTION
**Pull request by damsfx**

### CODE REVIEW

**Comment by mjauvin** [comment]
Merci!

**Comment by damsfx** [comment]
> Merci!

De rien ! ;o)

I use a quick command to compare translation files : 
```bash
> php artisan h3d:checktranslations plugins/winter/blocks/ en fr

Comparing translations.

Missing EN translations found
+----------------------------------+-------------------------------+
| EN keys missing in FR            | Value                         |
+----------------------------------+-------------------------------+
| missing_en                       | New EN key missing in FR      |
| actions.open_url.missing_deep_en | New EN deep key missing in FR |
+----------------------------------+-------------------------------+

Extras FR translations found
+----------------------------------+------------------------------------+
| Extras FR keys not found in EN   | Value                              |
+----------------------------------+------------------------------------+
| extra_fr                         | Extra FR key no more required      |
| actions.open_media.extra_deep_fr | Extra FR deep key no more required |
+----------------------------------+------------------------------------+
```

**Comment by LukeTowers** [comment]
@damsfx feel free to submit that command as a PR to the winter core, maybe as a `winter:util` subcommand for now

**Comment by LukeTowers** [comment]
We also have support for programmatically interacting with the localization files now so perhaps we could add support for making the changes directly from the command line as well! 🤯

**Pull request merged**
